version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accessly_frontend
    ports:
      - "3001:3001"   
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000  # backend endpoint
    volumes:
      - /app/node_modules
    restart: unless-stopped
